AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyEC2Instance:
    Type: "AWS::AutoScaling::AutoScalingGroup"
 Properties: 
  AutoScalingGroupName: 'ToniBennPracticeASG'
  AvailabilityZones: 
    'us-east-1'
  CapacityRebalance: '120'
  DesiredCapacity: '80'
  DesiredCapacityType: '2'
  HealthCheckGracePeriod: 300
  LaunchConfigurationName: 'PracticeRun'
  LaunchTemplate: 
    'PracticeRun'
  MaxSize: '5'
  MinSize: '2'
