AWSTemplateFormatVersion" : "2010-09-09"

Type: AWS::AutoScaling::AutoScalingGroup
Properties: 
  AutoScalingGroupName: ToniBennPracticeASG
  AvailabilityZones: 
    'us-east-1'
  CapacityRebalance: '120'
  DesiredCapacity: '80'
  DesiredCapacityType: 'cpu'
  HealthCheckGracePeriod: 0
  LaunchConfigurationName: 'PracticeRun'
  LaunchTemplate: 
    'PracticeRun'
  MaxSize: '5'
  MetricsCollection: 
    - MetricsCollection
  MinSize: '2'
