AWSTemplateFormatVersion: '2010-09-09'
Resources:
  myLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateName: !Sub ${AWS::StackName}-launch-template
      LaunchTemplateData: 
        ImageId: ami-0a8b4cd432b1c3063
        InstanceType: t3.nano
        KeyName: Practicerun
        Monitoring: 
          Enabled: true
        SecurityGroupIds: 
          - sg-0a14eb590a4d09d43
  myASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: ToniBASG1
      Availability Zone: us-east-1 
      MinSize: "2"
      MaxSize: "5"
      DesiredCapacity: "2"
      HealthCheckGracePeriod: 300
      LaunchTemplate:
        LaunchTemplateId: !Ref myLaunchTemplate
        Version: !GetAtt myLaunchTemplate.LatestVersionNumber
      MetricsCollection: 
        - Granularity: "1Minute"
          Metrics: 
            - "2"
            - "5"
